### ISSUE TITLE
reorder needed in file led_strip_create_no_backend.c

### ISSUE THREAD

**Issue by PeterSchober** [tderensis/led_strip#1]
Variable is used before value has been set
File: led_strop_ne_backend.c
	Function: led_strip_t * led_strip_create_no_backend(uint32_t num_leds)
		Variable Line 51. led_strip->num_leds = num_leds;
		
		
Solution:
	Move Line 51 to begin of function. (e.g. Line 25)

**Comment by tderensis** [comment]
Thank you for reporting this! Fixed in commit d157fd69dde8b908e9451d33e25a49a672069c6f
